### ISSUE TITLE
Problemas para build na imagem do gateway

### ISSUE THREAD

**Issue by gvictor00** [CESARBR/knot-gateway-buildroot#1]
Estou com problemas para criar a imagem do gateway. Fiz o processo descrito no arquivo **instructions_to_build_gateway_image.txt** (do zip [knot_v01.00](https://drive.google.com/file/d/0B-1By--bu9mTWnZERk1tZGRXaWM/view)), alterando a linha BR2_GATEWAY_HARDWARE=configs/raspberrypi2_defconfig make knot_gateway para BR2_GATEWAY_HARDWARE=configs/**raspberrypi3**_defconfig make knot_gateway e fiz o make.

Depois desse processo, fiz o passo 4) do arquivo para executar o script create_boot_disk.sh. As ultimas linhas da execução desse script recebi o seguinte output.

Copying bootloader files...
dd: falhou em abrir 'output/images/boot.vfat': Arquivo ou diretório não encontrado
Copying root filesystem...
dd: falhou em abrir 'output/images/rootfs.ext4': Arquivo ou diretório não encontrado
resize2fs 1.42.13 (17-May-2015)
resize2fs: Bad magic number in super-block tentando abrir /dev/sdb2
Não se pôde encontrar superbloco de sistema válido.
Done!
Please remove the sdcard and boot the board.

Consequentemente, não consegui dar boot no cartão. Alguma sugestão?

**Comment by rodrigoalves1** [comment]
@gvictor00 foi mal a demora, você conseguiu contornar o problema?

**Comment by gvictor00** [comment]
@rodrigoalves1 eu resolvi. Isso era problema nas libs do meu Linux. Acabei que consegui achar na internet quais libs, além daquelas descritas aqui no git, que eu precisava baixar.

**Comment by jcorde** [comment]
Hi, @ramonhpr. Would you please check if this issue is still valid? If not, please sign me to close it

**Comment by ramonhpr** [comment]
@jcorde I think you can close it as who opens the issue said that could solve the problem.
Besides this, we will no longer more use `create-boot-disk.sh` because now we can flash the `sdcard.img` generated by buildroot, since it creates the `/data` partition.
